---
output:
  md_document:
    variant: markdown_github
---

## 2016-11-27

* Ran the model with data through 2016-11-26.
* New feature: removing injured players and capturing dates players are expected to return from injury. If the return date is not available -- e.g., due to game-day decision -- I hold the player out for one day.
* Fixed bug that caused forecasts (not back-casts) to miss the data from the last actual game day. 

## 2016-12-04

* Ran the model with data through 2016-12-03.
* Cleveland fell in the rankings (to number 5), while Houston, Clippers, San Antonio and Golden State are looking strong.

## 2016-12-11

* Ran the model with data through 2016-12-10.
* Houston and Toronto made big gains in the rankings.

## 2016-12-18

* Ran the model with data through 2016-12-17
* Golden State and Houston are still looking strong, with Golden State being the clear favorite. Interestingly, the Clippers fell below Utah, Memphis and Toronto to number 7 overall. FiveThirtyEight has the Clippers tied with Toronto at number 5.

## 2016-12-25

* Ran the model with data through 2016-12-24
* Golden State still on top. Cleveland and San Antonio tied at number 2. Houston and Toronto right behind.

## 2017-01-01

* Ran the model with data through 2016-12-31
* A shocking development: Golden State dropped to number three overall! Could it be because they have not done that well against elite teams do far?
