---
title: "readme"
output: html_document
---

# Black Box NBA Team Rankings

## Introduction

After the 2016 presidential election, most people will probably argue that the last thing the world needs is another statistical prediction model. It's safe to say that the failure of the election models added to the element of shock and surprise on both sides of the political spectrum.

So does this mean that we should we turn our backs on prediction models? Of course not, we just need to revise our expectations. The famous statistician George Box once reminded us that statistical models can never *exactly* represent the real world; models are at best useful *approximations* of the real world. Also, models are only as good as its inputs and assumptions: if the inputs are bad -- such as incorrect polls -- the model is wrong. If the unthinkable happens, the model wouldn't have predicted it unless unthinkable assumptions were made.

Now, what does this have to do with the NBA? Basketball is a perfect example of a structured world with lots of information about what is happening today and lots of uncertainty around the future. If a team looks great on paper and is winning games, it'll likely do well in the future. But team chemistry, injuries, coaching changes, trades etc. can curtial success very quickly. Thus, any model-based prediction can only be viewed simply a benchmark for future success. 

This post discusses a new approach to predicting the outcome of NBA games. I've been sharing insigts from this model in prior posts about the Golden State Warriors and thohght it was time to share some broader results. I have no doubt the modes is wrong, but hopefully it's useful.


# How it Works

The Elastic NBA Team Rankings is a dynamic ranking algorithm that is purely based on statistical modeling techniques commonly used across most industries. No qualitative data or judgment is used to decide the ranks; the only human judgment applied is the underlying mental model behind the algorithm.

At a high level, the model depends on three overall factors:

* Previous performance.
* The team "DNA" as measured by the roster composition of "player archetypes."
* Circumstances -- e.g., traveling, rest days, home court advantage.

More specifically, the model is based on three-step procedure:

1. Group players into 25 *archetypes* using (k-means) clustering based on box-score stats. The archetype definitions were created using data prior to the 2016-2017 season; players are matched to the cluster based on their historical performance leading up to a given game. Note that from a technical perspective, the goal of the clustering algorithm is to maximize similarity of players (in terms of offensive and defensive stats) *within* clusters, while minimizing differences *between* clusters.
2. For every future game of the 2016-2017 season, predict the winner of a given game, based on the team archetypes, home team advantage, rest days, miles traveled, as well as in-season previous matchup outcomes and win-percentages.
3. Rank teams based on the predicted future win rate.

Now, why the name "Black Box

## Some Notes on the Model Used in Step 2
The model used to predict the winner of a given game is a statistical model that is estimated based on the most recent 365 "game days." Hence, the relative weights of the various drivers -- for example, the importance of different archetypes versus win percentages -- are purely based on the relationship detected from the data. For the stats-minded readers, the model is a logistic regression with an L1 penalty (lasso) to reduce the chance of overfitting (this worked best in back-testing).

The model is re-estimated every single day and contains the following variables:

*  Surpluses and deficits of minutes allocated to the different archetypes. For example, if a team's lineup has more players on the court of archetype 1 than its opponent, it'll have a surplus of minutes allocated to that archetype, and vice versa for deficits. These variables basically compare the "DNAs" of the rosters.
* Short term and long term trailing winning percentages. Short term is 30 days and long term is 60 days. The winning percentages are interacted with time, which results in the model assigning less importance to win-streaks early in the season.
* Previous matchup outcomes. For example, let's say Golden State is playing the Clippers and the two teams have played eachother earlier in the season. This variable captures the outcomes of those two games. A team is more likely to win if it beat its opponent in the past.
* Distances traveled prior to the game. Traveling the day before games usually translates into weaker performances, holding everything else constant.
* Rest days prior to games. Obviously, more rest of beneficial during the long NBA season.
* Home team advantage.

## How Are Players Assigned to Archetypes?

The outcome of the k-means clustering routine used create the archetypes is a set of *centroids*. Players are assigned to archetypes by matching their offensive and defensive box score statistics to closest centroids using a simple Euclidian distance. A decay funtion was applied such that more recent games receive a larger weight. On top of that, games played in the previous season are discounted by a factor of 4.

## Predicting Allocation of Minutes for Future Games

In order to calculate the deficit and surplus variables referenced above, it's necessary to predict which players will be playing in a given game and how many minutes each player will play. Currently, a recency/frequency approach is used to guess who will suit up for a given team. Basically, the 13 players that are played most frequently and recently for a given team will ve added to the roster.

In terms of predicting the number of minutes each person will play, a 90-day trailing window is used (excluding the offseason). Games played during the prior season are discounted by a factor of 4.










## Including Plots

You can also embed plots, for example:
